version: '3.9'

services:

  postgres:
    # SPDX-SnippetBegin
    # SPDX-SnippetCopyrightText: Copyright (c) 2025 Software GmbH, Darmstadt, Germany and/or its subsidiaries and/or its affiliates
    # SPDX-License-Identifier: Apache-2.0
    # SPDX-FileContributor: Modified by Software GmbH
    image: library/postgres:${KC_POSTGRES_IMAGE_TAG:-15}
    # SPDX-SnippetEnd
    container_name: "aas-db-server"
    # SPDX-SnippetBegin
    # SPDX-SnippetCopyrightText: Copyright (c) 2025 Software GmbH, Darmstadt, Germany and/or its subsidiaries and/or its affiliates
    # SPDX-License-Identifier: Apache-2.0
    # SPDX-FileContributor: Modified by Software GmbH
    restart: unless-stopped
    # SPDX-SnippetEnd
    volumes:
      - ./postgres-initdb-scripts:/docker-entrypoint-initdb.d
    environment:
      # SPDX-SnippetBegin
      # SPDX-SnippetCopyrightText: Copyright (c) 2025 Software GmbH, Darmstadt, Germany and/or its subsidiaries and/or its affiliates
      # SPDX-License-Identifier: Apache-2.0
      # SPDX-FileContributor: Modified by Software GmbH
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      # SPDX-SnippetEnd
      POSTGRES_MULTIPLE_DATABASES: aas, keycloak
      # SPDX-SnippetBegin
      # SPDX-SnippetCopyrightText: Copyright (c) 2025 Software GmbH, Darmstadt, Germany and/or its subsidiaries and/or its affiliates
      # SPDX-License-Identifier: Apache-2.0
      # SPDX-FileContributor: Modified by Software GmbH
      PGPORT: 5433
      # SPDX-SnippetEnd
    healthcheck:
      # SPDX-SnippetBegin
      # SPDX-SnippetCopyrightText: Copyright (c) 2025 Software GmbH, Darmstadt, Germany and/or its subsidiaries and/or its affiliates
      # SPDX-License-Identifier: Apache-2.0
      # SPDX-FileContributor: Modified by Software GmbH
      test: pg_isready -d postgres -U postgres
      # SPDX-SnippetEnd
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    ports:
      # SPDX-SnippetBegin
      # SPDX-SnippetCopyrightText: Copyright (c) 2025 Software GmbH, Darmstadt, Germany and/or its subsidiaries and/or its affiliates
      # SPDX-License-Identifier: Apache-2.0
      # SPDX-FileContributor: Modified by Software GmbH
      - ${KC_POSTGRES_PORT_MAPPING:-5433}:5433
      # SPDX-SnippetEnd
    networks:
      - "gaia-x"
    deploy:
      resources:
        limits:
          # SPDX-SnippetBegin
          # SPDX-SnippetCopyrightText: Copyright (c) 2025 Software GmbH, Darmstadt, Germany and/or its subsidiaries and/or its affiliates
          # SPDX-License-Identifier: Apache-2.0
          # SPDX-FileContributor: Modified by Software GmbH
          memory: 512M
          # SPDX-SnippetEnd

  # SPDX-SnippetBegin
  # SPDX-SnippetCopyrightText: Copyright (c) 2025 Software GmbH, Darmstadt, Germany and/or its subsidiaries and/or its affiliates
  # SPDX-License-Identifier: Apache-2.0
  # SPDX-FileContributor: Modified by Software GmbH
  keycloak:
    container_name: "aas-key-server"
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_PORT: 5433
      DB_SCHEMA: public
      DB_DATABASE: keycloak
      DB_USERNAME: ${KEYCLOAK_DB_USERNAME}
      DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KC_FEATURES: preview
      KEYCLOAK_ADMIN: "${KEYCLOAK_ADMIN}"
      KEYCLOAK_ADMIN_PASSWORD: "${KEYCLOAK_ADMIN_PASSWORD}"
    image: "quay.io/keycloak/keycloak:${KEYCLOAK_VERSION}"
    ports:
      - "8080:8080"
    extra_hosts:
      - "auth-server:host-gateway"
    networks:
      - "gaia-x"
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - "../keycloak/providers:/opt/keycloak/providers"
      - "../keycloak/realms_local:/opt/keycloak/data/import"    
    command:
      [
          'start --hostname-strict-https false --hostname-strict false --proxy edge --http-enabled true --import-realm ',
#       --spi-user-profile-legacy-user-profile-read-only-attributes *_RES_ACCESS_MODE
          '--log-level=DEBUG,io.quarkus:INFO,liquibase:INFO,org.hibernate:INFO,org.infinispan:INFO,org.keycloak.services.scheduled:INFO,org.keycloak.transaction:INFO,io.netty.buffer.PoolThreadCache:INFO,org.keycloak.models.sessions.infinispan:INFO'
      ]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8080/realms/master"]
      start_period: 10s
      interval: 30s
      retries: 3
      timeout: 5s
  # SPDX-SnippetEnd

  aas:
    build:
      context: ../service
      dockerfile: Dockerfile
    container_name: "aas-auth-server"
    environment:
      SPRING_PROFILES_ACTIVE: "${PROFILES_AAS}"
      # SPDX-SnippetBegin
      # SPDX-SnippetCopyrightText: Copyright (c) 2025 Software GmbH, Darmstadt, Germany and/or its subsidiaries and/or its affiliates
      # SPDX-License-Identifier: Apache-2.0
      # SPDX-FileContributor: Modified by Software GmbH
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5433/aas
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - "./demo:/opt/demo"
      # SPDX-SnippetEnd
    ports:
      - "9000:9000"
    networks:
      - "gaia-x"
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy

# SPDX-SnippetBegin
# SPDX-SnippetCopyrightText: Copyright (c) 2025 Software GmbH, Darmstadt, Germany and/or its subsidiaries and/or its affiliates
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileContributor: Modified by Software GmbH
#  app:
#    build:
#      context: ../app
#      dockerfile: Dockerfile
#    container_name: "aas-test-server"
#    environment:
#      SPRING_PROFILES_ACTIVE: "${PROFILES_AAS}"
#      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI: http://key-server:8080/realms/gaia-x
#    extra_hosts:
#      - "key-server:host-gateway"
#    ports:
#      - "8990:8990"
#    networks:
#      - "gaia-x"
#    restart: unless-stopped
#    depends_on:
#      keycloak:
#        condition: service_healthy

networks:
  gaia-x:
    name: "gx_docker"
    driver: "bridge"
# SPDX-SnippetEnd
