server:
  port: 8180
spring:
  application:
    name: cip-app
  mvc:
    log-request-details: true    

keycloak:
  auth-server-url: ${AUTH_SERVER_URL}
  realm: gaia-x
  ssl-required: external
  resource: cip-app
  credentials:
    secret: ${KEYCLOAK_SECRET}
  principal-attribute: ${PRINCIPAL_ATTRIBUTE}
  bearer-only: false
  enable-basic-auth: true
  cors: true
#  
  security-constraints:
    - auth-roles:
      - "*"
    - security-collections:
      - patterns:
        - /*
#         
  policy-enforcer-config:
    enforcement-mode: ENFORCING
    lazy-load-paths: true
    paths:
      - path: /sso/login
        enforcement-mode: DISABLED
        methods:
          - method: GET
#
      - path: /demo
        enforcement-mode: DISABLED
        methods:
          - method: GET
#
      - path: /demo/read
        enforcement-mode: DISABLED
        scopes:
          - openid
          - profile
        claim-information-point-config:
          http:
            method: GET
            url: ${CLAIM_INFO_URL_READ}
            parameters:
              usr: "{keycloak.access_token['/sub']}"
              sub: "{keycloak.access_token['/${PRINCIPAL_ATTRIBUTE}']}"
              scope: openid profile email
#
      - path: /demo/write
        enforcement-mode: DISABLED
        claim-information-point-config: 
          http:
            method: GET
            url: ${CLAIM_INFO_URL_WRITE}
            parameters:
              usr: "{keycloak.access_token['/sub']}"
              sub: "{keycloak.access_token['/${PRINCIPAL_ATTRIBUTE}']}"
              scope: openid

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    org.keycloak.adapters.OAuthRequestAuthenticator: DEBUG    
